// Mascot catalog for HoldWise AI — an original cast of animated playing-card
// characters. Artwork is generated; mood is conveyed through Framer Motion.
// "none" is a valid choice — users may opt out of the companion entirely.

export const MASCOTS = [
  {
    id: "ace",
    name: "Coach Ace",
    card: "Ace of Spades",
    role: "Your personal coach",
    image: "https://media.base44.com/images/public/6a62ea494502af47c9aaab8a/6bc146f5f_generated_image.png",
    worldId: null,
    accent: "hsl(var(--hw-gold))",
    suitSymbol: "♠",
    personality: "Patient, wise, encouraging, calm, lightly funny, never judgmental.",
    teaches: ["Overall learning path","Video-poker strategy","Pay tables","Expected value","Advanced explanations","Progress reviews","Responsible learning"],
    bio: "The primary guide and face of HoldWise. An Ace of Spades card brought to life with a teacher's pointer and reading glasses, here to make difficult concepts feel simple.",
    phrase: "Every expert started with one card.",
    lines: { idle: ["Nice to see you! Ready for a hand?","Every decision is a chance to learn.","Take it one card at a time.","No pressure. Let's look at the hand together."], happy: ["Nice — that was the right hold!","You're getting it!","Spot on. Let's keep going.","Slow and correct beats fast and confused."], celebrate: ["Fantastic work!","Streak alive — you're on fire.","Level up! So proud of you.","You did not fail the hand. You found the next thing to learn."], sad: ["That one got away — let's review it.","Almost. Here's why it mattered.","No worries, mistakes are lessons.","That decision was close. Here's the detail that separates the two."], thinking: ["Hmm, let's think this through…","What does the strategy say here?","Good question — let me check."], talk: ["Here's the idea…","So the key is…","Let me explain…"] },
  },
  { id: "jax", name: "Jax", card: "Jack of Hearts", role: "Ranks, face cards & quizzes", image: "https://media.base44.com/images/public/6a62ea494502af47c9aaab8a/20409fdc6_generated_image.png", worldId: "world-3", accent: "hsl(0 70% 62%)", suitSymbol: "♥", personality: "Energetic, funny, competitively healthy, loves quizzes and streaks.", teaches: ["Card ranks","Face cards","Jacks or Better","High pairs","Fast recognition drills","Daily challenges","Quiz sessions"], bio: "The Jack of Hearts — fast, expressive, and full of memory tricks and rhymes. Great with users who feel nervous; he celebrates every streak.", phrase: "Jack spotted! That pair is officially in the payment neighborhood.", lines: { idle: ["Quick eyes win the hand!","Ready for a rapid drill?","Spot the Jack, hold the pair.","Let's rack up a streak."], happy: ["Quick eyes, smart hold!","Nice catch!","I almost fooled you with that one. Almost."], celebrate: ["Streak! Let's keep it rolling!","Quiz champ!","Jack spotted — payment neighborhood!"], sad: ["So close! Run it back.","Almost — check the rank.","No sweat, we'll get the next one."], thinking: ["Which rank matches?","Count the face cards…"], talk: ["A high pair is Jacks or better…","Face cards are J, Q, K…"] } },
  { id: "vee", name: "Queen Vee", card: "Queen of Diamonds", role: "Suits, rankings & pay tables", image: "https://media.base44.com/images/public/6a62ea494502af47c9aaab8a/c7baa1c29_generated_image.png", worldId: "world-2", accent: "hsl(45 70% 60%)", suitSymbol: "♦", personality: "Clear, organized, detail-oriented, calm when correcting mistakes.", teaches: ["Suits","Matching","Poker-hand rankings","Pay-table reading","Visual comparisons","Straight vs flush","Two pair vs three of a kind"], bio: "The Queen of Diamonds — elegant, precise, and excellent at visual explanations. She separates ideas that look alike so you never confuse them again.", phrase: "A straight follows rank order. A flush follows suit.", lines: { idle: ["Let's climb the hand ladder.","Order the ranks, name the hand.","Same suit doesn't mean same rank."], happy: ["Beautiful pattern — named correctly.","Right hand, right call!","You spotted it."], celebrate: ["Hand-ladder champion!","Rankings mastered!","Elegant work."], sad: ["Let's separate those ideas.","Compare the ranks again.","Close — count the matching cards."], thinking: ["Which ranks match here?","Straight or flush — which rule applies?"], talk: ["A pair is two of the same rank…","A flush is all one suit…"] } },
  { id: "king", name: "King Club", card: "King of Clubs", role: "Made hands & fundamentals", image: "https://media.base44.com/images/public/6a62ea494502af47c9aaab8a/7b104ee15_generated_image.png", worldId: "world-4", accent: "hsl(150 28% 45%)", suitSymbol: "♣", personality: "Steady, protective, traditional, practical, plain-spoken.", teaches: ["Made hands","Holding pairs","Three of a kind","Full houses","Four of a kind","Conservative fundamentals","Reviewing common mistakes"], bio: "The King of Clubs — a steady protector of strong hands. He reminds you to respect what you've built before chasing what you might draw.", phrase: "Protect the hand you have before dreaming about the hand you might draw.", lines: { idle: ["Respect the made hand.","Fundamentals first.","Don't tear down the house."], happy: ["A made pair deserves respect.","Strong read!","You held the right cards."], celebrate: ["Full house! The fundamentals held.","Four of a kind — majestic!","The kingdom stands."], sad: ["Don't break that made hand.","Protect what you built.","Chasing a window cost you here."], thinking: ["Is this a made hand or a draw?","What beats this on the draw?"], talk: ["Three of a kind is three of one rank…","A full house is a pair plus three…"] } },
  { id: "deuce", name: "Deuce", card: "Two of Clubs", role: "Card basics for beginners", image: "https://media.base44.com/images/public/6a62ea494502af47c9aaab8a/a6c6bd830_generated_image.png", worldId: "world-1", accent: "hsl(200 60% 60%)", suitSymbol: "♣", personality: "Curious, relatable, beginner-friendly, asks the questions you might not.", teaches: ["Absolute card basics","What a deck is","Red versus black","Higher and lower ranks","Pairs","Beginner terminology","First-time lessons"], bio: "The Two of Clubs — small, curious, and learning right alongside you. Asks the questions beginners are too shy to ask, and celebrates every small victory.", phrase: "We are not behind. We are building the foundation.", lines: { idle: ["Let's start at the very beginning.","52 cards, four suits — easy!","Rank and suit are different? I had to learn that too."], happy: ["Two matching ranks make a pair!","You've got it!","Small win, big step."], celebrate: ["Foundation built!","You know your deck!","We're not behind — we're building."], sad: ["Let's look again together.","No rush — try once more.","Mistakes are how Deuce learns too."], thinking: ["Which symbol is the suit?","Higher or lower — which way?"], talk: ["A deck has 52 cards…","Hearts and Diamonds are red…"] } },
  { id: "spade", name: "Spade", card: "Spades suit symbol", role: "Silent helper & pointer", image: "https://media.base44.com/images/public/6a62ea494502af47c9aaab8a/ca89ba1c3_generated_image.png", worldId: null, accent: "hsl(var(--hw-gold))", suitSymbol: "♠", silent: true, personality: "Expressive without words. Points, reacts, hides, and celebrates.", teaches: ["Loading animations","Pointing to buttons","Empty states","Achievement reactions"], bio: "Not a full card — just a lively Spades symbol with tiny eyes and white gloves. Speaks only through gestures and expressions. The app's secondary icon character.", phrase: "♠", lines: { idle: ["♠"], happy: ["♠!"], celebrate: ["♠♠!"], sad: ["♠…"], thinking: ["♠?"], talk: ["♠"] } },
  { id: "hearty", name: "Hearty", card: "Heart suit", role: "Family card games", image: null, worldId: null, accent: "hsl(0 70% 62%)", suitSymbol: "♥", premium: true, personality: "Warm and inviting.", teaches: ["Go Fish","Old Maid","Crazy Eights"], bio: "A warm Heart suit mascot who guides learners through family card games.", phrase: "Let's play a round together.", lines: { idle: ["Pull up a chair — family games are better together.","Ready to match, ask, and laugh?"], happy: ["That was a kind and clever play!","You found the match!"], celebrate: ["Family-table champion!","Now that was a heart-smart round!"], sad: ["No worries — ask again on your next turn.","Let’s look at what is still in the hand."], thinking: ["What card would complete the match?","Who is most likely to hold it?"], talk: ["In family games, clear turns keep everybody in the fun.","Watch the ranks more than the suits here."] } },
  { id: "trickster", name: "Trickster Ten", card: "Ten card", role: "Trick-taking games", image: null, worldId: null, accent: "hsl(45 70% 60%)", suitSymbol: "♣", premium: true, personality: "Clever and quick-witted.", teaches: ["Spades","Hearts","Whist","Euchre"], bio: "A clever Ten card that teaches trick-taking strategy.", phrase: "Win the trick, win the round.", lines: { idle: ["Read the lead before you play.","Every trick leaves a clue."], happy: ["Sharp trick!","You followed suit and found the edge."], celebrate: ["Trick-taking masterclass!","That contract never stood a chance."], sad: ["Check the lead suit once more.","Save that trump for the right moment."], thinking: ["Can you follow suit?","Is this the moment to spend trump?"], talk: ["A trick is one card from each player.","The lead suit controls the trick unless trump steps in."] } },
  { id: "ginny", name: "Ginny", card: "Gin Rummy guide", role: "Sets, runs & discards", image: null, worldId: null, accent: "hsl(150 28% 45%)", suitSymbol: "♦", premium: true, personality: "Polished and precise.", teaches: ["Sets","Runs","Drawing","Discarding"], bio: "A polished Gin Rummy guide who teaches how to build melds.", phrase: "Every discard tells a story.", lines: { idle: ["Every discard tells a story.","Sets or runs — let’s build cleanly."], happy: ["That meld fits beautifully!","Smart discard."], celebrate: ["Gin! Clean hand, clean finish!","Your melds are shining."], sad: ["That discard helped the other hand.","Keep the flexible cards a little longer."], thinking: ["Does this card fit a set or a run?","Which discard reveals the least?"], talk: ["A set shares a rank; a run shares a suit in order.","Deadwood is what remains outside your melds."] } },
  { id: "sol", name: "Sol", card: "Solitaire guide", role: "Patience & planning", image: null, worldId: null, accent: "hsl(220 60% 60%)", suitSymbol: "♠", premium: true, personality: "Calm and methodical.", teaches: ["Patience","Planning","Card organization"], bio: "A calm Solitaire guide who teaches planning and patience.", phrase: "One move at a time.", lines: { idle: ["One move at a time.","Open hidden cards whenever you safely can."], happy: ["That move created space!","Patient and precise."], celebrate: ["Table cleared!","Patience paid off."], sad: ["That move blocked a useful lane.","Let’s rewind and protect the empty space."], thinking: ["Which move uncovers new information?","Can a lower card move onto the opposite color?"], talk: ["Solitaire rewards moves that reveal hidden cards.","Empty columns are powerful — use them with a plan."] } },
  { id: "chip", name: "Chip", card: "Learning medal", role: "Progress rewards", image: null, worldId: null, accent: "hsl(var(--hw-gold))", suitSymbol: "★", premium: true, personality: "Cheerful and rewarding.", teaches: ["Lesson completion","Mastery","Achievements"], bio: "A small round learning-medal mascot that represents earned educational progress — never wagering credit.", phrase: "Another milestone earned!", lines: { idle: ["Progress is built one lesson at a time.","I keep the receipts on your growth."], happy: ["Milestone earned!","That mastery score just moved up."], celebrate: ["Achievement unlocked!","Look at that learning streak shine!"], sad: ["One rough round cannot erase your progress.","Review, retry, rise."], thinking: ["Which skill should we strengthen next?","Your mistake notebook has a useful clue."], talk: ["Learning points celebrate practice, never wagering.","Mastery grows when you revisit the hard parts."] } },
];

export const MASCOT_NONE = "none";
export function getMascot(id) { return MASCOTS.find((m) => m.id === id) || null; }
export function mascotForWorld(worldId) { return MASCOTS.find((m) => m.worldId === worldId) || getMascot("ace"); }
export function mascotLine(mascot, mood) { const m = getMascot(mascot) || getMascot("ace"); const pool = (m.lines[mood] || m.lines.idle) || m.lines.idle; return pool[Math.floor(Math.random() * pool.length)]; }
