import React, { useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Bot, Fish, Gauge, RotateCcw, Sparkles, Swords, Trophy } from 'lucide-react';
import GameShell from '@/components/games/GameShell';
import GlassSurface from '@/components/premium/GlassSurface';
import TactilePressable from '@/components/premium/TactilePressable';
import PlayingCard from '@/components/PlayingCard';
import { crazyEightsEngine, chooseCrazyEightsBotAction, startNextCrazyEightsRound } from '@/games/engines/crazyEights';
import { goFishEngine, chooseGoFishBotAction } from '@/games/engines/goFish';
import { warEngine } from '@/games/engines/war';
import { speedEngine, chooseSpeedBotAction } from '@/games/engines/speed';
import { colorClashEngine, chooseColorClashBotAction, startNextColorClashRound, COLOR_CLASH_COLORS } from '@/games/engines/colorClash';
import { recordGameResult } from '@/lib/cardAcademyProgress';
import './familyTable.css';

export const FAMILY_GAME_IDS=['crazy-eights','go-fish','war','speed','color-clash'];
const TITLES={'crazy-eights':'Crazy Eights','go-fish':'Go Fish',war:'War',speed:'Speed','color-clash':'Color Clash'};
const HUMAN=0;

function driveCrazy(input){let state=structuredClone(input),guard=0;while(!state.roundComplete&&!state.matchComplete&&state.actor!==HUMAN&&guard++<180)state=crazyEightsEngine.applyAction(state,chooseCrazyEightsBotAction(state,state.actor));if(guard>=180)throw new Error('Crazy Eights bot guard exceeded');return state;}
function driveFish(input){let state=structuredClone(input),guard=0;while(!goFishEngine.isTerminal(state)&&state.actor!==HUMAN&&state.actor!==null&&guard++<260)state=goFishEngine.applyAction(state,chooseGoFishBotAction(state,state.actor));if(guard>=260)throw new Error('Go Fish bot guard exceeded');return state;}
function driveSpeed(input){let state=structuredClone(input),guard=0;while(!speedEngine.isTerminal(state)&&!state.stalled&&state.actor!==HUMAN&&guard++<160)state=speedEngine.applyAction(state,chooseSpeedBotAction(state,state.actor));if(guard>=160)throw new Error('Speed bot guard exceeded');return state;}
function driveColor(input){let state=structuredClone(input),guard=0;while(!state.roundComplete&&!state.matchComplete&&state.actor!==HUMAN&&guard++<240){let action=chooseColorClashBotAction(state,state.actor);if(action.type==='play'&&state.players[state.actor].hand.length===2)action={...action,declareLastSpark:true};state=colorClashEngine.applyAction(state,action);}if(guard>=240)throw new Error('Color Clash bot guard exceeded');return state;}
function fresh(id,seed=20260815){if(id==='crazy-eights')return driveCrazy(crazyEightsEngine.createGame({seed,humanSeat:HUMAN,targetScore:100}));if(id==='go-fish')return driveFish(goFishEngine.createGame({seed,humanSeat:HUMAN}));if(id==='war')return warEngine.createGame({seed});if(id==='speed')return driveSpeed(speedEngine.createGame({seed,humanSeat:HUMAN}));return driveColor(colorClashEngine.createGame({seed,humanSeat:HUMAN,targetScore:250}));}

function Opponents({players,actor,extra}){return <div className="grid grid-cols-3 gap-2">{players.slice(1).map(player=><div key={player.seat} className={`hw-family-seat rounded-xl p-2 text-center ${actor===player.seat?'ring-1 ring-amber-300/45':''}`}><div className="flex items-center justify-center gap-1 text-[9px] font-black text-white/60"><Bot size={10}/>P{player.seat+1}</div><p className="mt-1 text-sm font-black text-white">{player.hand?.length??player.deck?.length??0}</p>{extra&&<p className="mt-1 text-[9px] text-white/38">{extra(player)}</p>}</div>)}</div>}

export default function FamilyTable({game}){
  const navigate=useNavigate();const id=FAMILY_GAME_IDS.includes(game?.id)?game.id:'crazy-eights';
  const [seed,setSeed]=useState(20260815);const [state,setState]=useState(()=>fresh(id));
  React.useEffect(()=>setState(fresh(id,seed)),[id]);
  const engine={ 'crazy-eights':crazyEightsEngine,'go-fish':goFishEngine,war:warEngine,speed:speedEngine,'color-clash':colorClashEngine }[id];
  const facts=engine.coachFacts(state,HUMAN);
  function newGame(){const next=seed+99991;setSeed(next);setState(fresh(id,next));}
  function record(previous,next){const priorDone=engine.isTerminal(previous)||previous.roundComplete;const nowDone=engine.isTerminal(next)||next.roundComplete;if(!priorDone&&nowDone){let won=false;if(id==='war'||id==='speed'||id==='go-fish')won=(engine.result(next)?.winners||[]).includes(HUMAN);else won=next.roundResult?.winner===HUMAN;recordGameResult(id,{family:id==='color-clash'?'family':'classics',won,xp:won?20:7});}}
  function commit(action){const previous=state;let next=engine.applyAction(state,action);if(id==='crazy-eights')next=driveCrazy(next);if(id==='go-fish')next=driveFish(next);if(id==='speed')next=driveSpeed(next);if(id==='color-clash')next=driveColor(next);record(previous,next);setState(next);}
  function nextRound(){let next=id==='crazy-eights'?startNextCrazyEightsRound(state):startNextColorClashRound(state);next=id==='crazy-eights'?driveCrazy(next):driveColor(next);setState(next);}
  return <GameShell game={{...game,title:TITLES[id]}} coachContext={{game:TITLES[id],facts}}><div className="mx-auto max-w-3xl"><div className="mb-2 flex gap-2 overflow-x-auto pb-1">{FAMILY_GAME_IDS.map(tab=><TactilePressable key={tab} onClick={()=>navigate(`/game/${tab}`)} className={`min-w-max rounded-xl px-3 py-2 text-[11px] font-black ${tab===id?'bg-[hsl(var(--hw-gold))] text-[hsl(var(--hw-navy))]':'bg-white/6 text-white shadow-none'}`}>{TITLES[tab]}</TactilePressable>)}</div><section className={`hw-family-table rounded-[2.4rem] p-3 sm:p-5 ${id==='color-clash'?'hw-family-spectrum':''}`}>{id==='crazy-eights'&&<CrazyBoard state={state} commit={commit}/>} {id==='go-fish'&&<FishBoard state={state} commit={commit}/>} {id==='war'&&<WarBoard state={state} commit={commit}/>} {id==='speed'&&<SpeedBoard state={state} commit={commit}/>} {id==='color-clash'&&<ColorBoard state={state} commit={commit}/>}</section><Completion id={id} state={state} engine={engine} nextRound={nextRound} newGame={newGame}/><p className="mt-2 text-center text-[10px] text-white/35"><Sparkles size={11} className="mr-1 inline hw-family-gold"/>Full rules · local AI · Coach Ace · complete win state · New Game</p></div></GameShell>;
}

function CrazyBoard({state,commit}){
  const [selected,setSelected]=useState(null),[chosenSuit,setChosenSuit]=useState('hearts');const legal=useMemo(()=>crazyEightsEngine.legalActions(state,HUMAN),[state]);const hand=state.players[HUMAN].hand;const selectedCard=hand.find(c=>c.id===selected);const play=selectedCard?.rank==='8'?legal.find(a=>a.type==='play'&&a.cardId===selected&&a.chosenSuit===chosenSuit):legal.find(a=>a.type==='play'&&a.cardId===selected);
  return <div><Opponents players={state.players} actor={state.actor}/><div className="hw-family-center mx-auto my-6 flex min-h-[180px] items-center justify-center gap-5 rounded-full"><div className="text-center"><p className="text-[9px] uppercase tracking-[.15em] text-white/35">Stock</p><button type="button" onClick={()=>legal.some(a=>a.type==='draw')&&commit({type:'draw',actor:HUMAN})} className="mt-2 h-24 w-16 rounded-xl hw-family-card-back"><span className="text-xs font-black text-white/65">{state.stock.length}</span></button></div><div className="text-center"><p className="text-[9px] uppercase tracking-[.15em] text-white/35">Discard · {state.currentSuit}</p><div className="mt-2"><PlayingCard card={state.discard.at(-1)}/></div></div></div><div className="flex overflow-x-auto pb-3"><div className="flex min-w-max -space-x-6 px-5">{hand.map(card=><div key={card.id} className={selected===card.id?'-translate-y-3':''}><PlayingCard card={card} selected={selected===card.id||legal.some(a=>a.cardId===card.id)} onClick={()=>setSelected(card.id)}/></div>)}</div></div>{selectedCard?.rank==='8'&&<div className="mt-2 grid grid-cols-4 gap-2">{['hearts','diamonds','clubs','spades'].map(suit=><TactilePressable key={suit} onClick={()=>setChosenSuit(suit)} className={`rounded-xl py-2 text-xs font-black ${chosenSuit===suit?'bg-[hsl(var(--hw-gold))] text-[hsl(var(--hw-navy))]':'bg-white/6 text-white shadow-none'}`}>{suit}</TactilePressable>)}</div>}<div className="mt-3 grid grid-cols-2 gap-2"><TactilePressable disabled={!play} onClick={()=>play&&commit({...play,actor:HUMAN})} className="rounded-2xl bg-[hsl(var(--hw-gold))] py-3 font-black text-[hsl(var(--hw-navy))]">Play card</TactilePressable>{legal.some(a=>a.type==='pass-drawn')?<TactilePressable onClick={()=>commit({type:'pass-drawn',actor:HUMAN})} className="rounded-2xl bg-white/7 py-3 font-black text-white shadow-none">Pass</TactilePressable>:<TactilePressable disabled={!legal.some(a=>a.type==='draw')} onClick={()=>commit({type:'draw',actor:HUMAN})} className="rounded-2xl bg-white/7 py-3 font-black text-white shadow-none">Draw</TactilePressable>}</div></div>;
}

function FishBoard({state,commit}){
  const [rank,setRank]=useState(state.players[HUMAN].hand[0]?.rank||'A'),[target,setTarget]=useState(1);const legal=useMemo(()=>goFishEngine.legalActions(state,HUMAN),[state]);const ranks=[...new Set(state.players[HUMAN].hand.map(c=>c.rank))];React.useEffect(()=>{if(!ranks.includes(rank)&&ranks.length)setRank(ranks[0]);},[state]);const ask=legal.find(a=>a.type==='ask'&&a.rank===rank&&a.target===target);
  return <div><Opponents players={state.players} actor={state.actor} extra={p=>`${p.books} book${p.books===1?'':'s'}`}/><div className="my-5 grid grid-cols-2 gap-3"><GlassSurface strength={2} className="rounded-2xl p-3 text-center"><Fish className="mx-auto hw-family-gold"/><p className="mt-1 text-[9px] uppercase tracking-[.15em] text-white/40">Pond</p><p className="text-xl font-black text-white">{state.stock.length}</p></GlassSurface><GlassSurface strength={2} className="rounded-2xl p-3 text-center"><Trophy className="mx-auto hw-family-gold"/><p className="mt-1 text-[9px] uppercase tracking-[.15em] text-white/40">Your books</p><p className="text-xl font-black text-white">{state.players[HUMAN].books}</p></GlassSurface></div><div className="flex overflow-x-auto pb-3"><div className="flex min-w-max -space-x-6 px-5">{state.players[HUMAN].hand.map(card=><PlayingCard key={card.id} card={card} selected={card.rank===rank} onClick={()=>setRank(card.rank)}/>)}</div></div><div className="mt-3"><p className="text-[9px] font-black uppercase tracking-[.15em] text-white/40">Ask for rank {rank}</p><div className="mt-2 grid grid-cols-3 gap-2">{[1,2,3].map(seat=><TactilePressable key={seat} onClick={()=>setTarget(seat)} className={`rounded-xl py-2 text-xs font-black ${target===seat?'bg-[hsl(var(--hw-gold))] text-[hsl(var(--hw-navy))]':'bg-white/6 text-white shadow-none'}`}>Player {seat+1}</TactilePressable>)}</div><TactilePressable disabled={!ask} onClick={()=>ask&&commit(ask)} className="mt-3 w-full rounded-2xl bg-[hsl(var(--hw-gold))] py-3 font-black text-[hsl(var(--hw-navy))]">Go Fish · Ask {rank}</TactilePressable>{state.lastEvent&&<p className="mt-2 text-center text-xs text-white/45">{state.lastEvent.type==='got-cards'?`Got ${state.lastEvent.count} card${state.lastEvent.count===1?'':'s'}!`:state.lastEvent.luckyFish?'Lucky fish — you drew the rank you asked for!':'Go Fish.'}</p>}</div></div>;
}

function WarBoard({state,commit}){
  const result=warEngine.result(state);const last=state.lastBattle?.reveals?.at(-1);
  return <div className="py-4 text-center"><div className="grid grid-cols-2 gap-4"><GlassSurface strength={3} className="rounded-3xl p-4"><p className="text-[9px] uppercase tracking-[.15em] text-white/40">Your deck</p><p className="mt-1 text-2xl font-black text-white">{state.players[0].deck.length}</p></GlassSurface><GlassSurface strength={3} className="rounded-3xl p-4"><p className="text-[9px] uppercase tracking-[.15em] text-white/40">Opponent</p><p className="mt-1 text-2xl font-black text-white">{state.players[1].deck.length}</p></GlassSurface></div><div className="hw-family-center mx-auto my-5 rounded-[2rem] p-5">{last?<div className="flex items-center justify-center gap-5"><div><p className="mb-2 text-[9px] font-black uppercase tracking-[.14em] text-white/40">You</p><PlayingCard card={last.you}/></div><div><Swords size={30} className="mx-auto hw-family-gold"/><p className="mt-2 font-heading text-xl font-black text-white">{state.lastBattle?.warDepth?`WAR ×${state.lastBattle.warDepth}`:'Battle'}</p></div><div><p className="mb-2 text-[9px] font-black uppercase tracking-[.14em] text-white/40">Opponent</p><PlayingCard card={last.opponent}/></div></div>:<><Swords size={34} className="mx-auto hw-family-gold"/><p className="mt-2 font-heading text-2xl font-black text-white">Battle</p></>}<p className="mt-3 text-xs text-white/45">Battle #{state.battleNumber+1}{state.lastBattle?.winner===0?' · You took the pot':state.lastBattle?.winner===1?' · Opponent took the pot':''}</p></div>{!result.complete&&<TactilePressable onClick={()=>commit({type:'battle'})} className="w-full rounded-2xl bg-[hsl(var(--hw-gold))] py-4 text-lg font-black text-[hsl(var(--hw-navy))]">Battle</TactilePressable>}</div>;
}

function SpeedBoard({state,commit}){const legal=useMemo(()=>speedEngine.legalActions(state,HUMAN),[state]);return <div><div className="flex items-center justify-between"><div><p className="text-[9px] uppercase tracking-[.15em] text-white/40">Opponent</p><p className="text-lg font-black text-white">{state.players[1].hand.length+state.players[1].stock.length} left</p></div><Gauge className="hw-family-gold"/><div className="text-right"><p className="text-[9px] uppercase tracking-[.15em] text-white/40">You</p><p className="text-lg font-black text-white">{state.players[0].hand.length+state.players[0].stock.length} left</p></div></div><div className="hw-family-center my-6 rounded-full p-5"><div className="flex items-center justify-center gap-5">{state.center.map((card,pile)=><div key={pile} className="hw-speed-center rounded-2xl p-2"><PlayingCard card={card}/><p className="mt-1 text-[9px] text-white/35">Reserve {state.reserves[pile].length}</p></div>)}</div></div><div className="flex justify-center gap-2">{state.players[HUMAN].hand.map(card=>{const moves=legal.filter(a=>a.type==='play'&&a.cardId===card.id);return <div key={card.id}><PlayingCard card={card} selected={moves.length>0} onClick={moves.length?()=>commit(moves[0]):undefined}/></div>})}</div><div className="mt-4 grid grid-cols-2 gap-2">{legal.some(a=>a.type==='flip-reserves')&&<TactilePressable onClick={()=>commit({type:'flip-reserves',actor:HUMAN})} className="rounded-2xl bg-[hsl(var(--hw-gold))] py-3 font-black text-[hsl(var(--hw-navy))]">Flip Reserves</TactilePressable>}{legal.some(a=>a.type==='pass')&&<TactilePressable onClick={()=>commit({type:'pass',actor:HUMAN})} className="rounded-2xl bg-white/7 py-3 font-black text-white shadow-none">Yield beat</TactilePressable>}</div></div>}

const CC_ICONS={block:'⊘','flip-flow':'↔','surge-two':'+2','color-shift':'◇','prism-four':'+4'};
function ClashCard({card,selected,onClick}){const text=card.type==='number'?card.number:CC_ICONS[card.symbol]||card.symbol;return <button type="button" onClick={onClick} className={`hw-cc-card ${card.color||'spectrum'} ${selected?'selected':''}`}><span className="absolute left-2 top-2 text-sm">{text}</span><span className="absolute inset-0 flex items-center justify-center text-3xl">{text}</span><span className="absolute bottom-2 right-2 rotate-180 text-sm">{text}</span></button>}
function ColorBoard({state,commit}){
  const [selected,setSelected]=useState(null),[chosenColor,setChosenColor]=useState('ember'),[lastSpark,setLastSpark]=useState(false);const legal=useMemo(()=>colorClashEngine.legalActions(state,HUMAN),[state]);const hand=state.players[HUMAN].hand,card=hand.find(c=>c.id===selected),play=card?.type==='wild'||card?.type==='wild4'?legal.find(a=>a.type==='play'&&a.cardId===selected&&a.chosenColor===chosenColor):legal.find(a=>a.type==='play'&&a.cardId===selected);
  return <div><Opponents players={state.players} actor={state.actor}/><div className="hw-family-center my-5 flex items-center justify-center gap-5 rounded-full p-4"><div className="text-center"><p className="text-[9px] uppercase tracking-[.15em] text-white/35">Draw</p><button type="button" onClick={()=>legal.some(a=>a.type==='draw')&&commit({type:'draw',actor:HUMAN})} className="mt-2 h-[104px] w-[70px] rounded-2xl hw-family-card-back"><span className="text-xs font-black text-white">{state.stock.length}</span></button></div><div className="text-center"><p className="text-[9px] uppercase tracking-[.15em] text-white/35">Current · {state.currentColor}</p><div className="mt-2"><ClashCard card={state.discard.at(-1)}/></div></div></div><div className="flex overflow-x-auto pb-4"><div className="flex min-w-max -space-x-5 px-5">{hand.map(item=><ClashCard key={item.id} card={item} selected={selected===item.id||legal.some(a=>a.cardId===item.id)} onClick={()=>setSelected(item.id)}/>)}</div></div>{(card?.type==='wild'||card?.type==='wild4')&&<div className="grid grid-cols-4 gap-2">{COLOR_CLASH_COLORS.map(color=><button type="button" key={color} onClick={()=>setChosenColor(color)} className={`min-h-[44px] rounded-xl hw-cc-color-${color} text-[10px] font-black uppercase text-white ${chosenColor===color?'ring-2 ring-amber-200':''}`}>{color}</button>)}</div>}{hand.length===2&&selected&&<label className="mt-3 flex min-h-[44px] items-center justify-center gap-2 rounded-xl border border-amber-200/15 bg-amber-200/5 px-3 text-xs font-black hw-family-gold"><input type="checkbox" checked={lastSpark} onChange={e=>setLastSpark(e.target.checked)}/>Last Spark</label>}<div className="mt-3 grid grid-cols-2 gap-2"><TactilePressable disabled={!play} onClick={()=>play&&commit({...play,actor:HUMAN,declareLastSpark:lastSpark})} className="rounded-2xl bg-[hsl(var(--hw-gold))] py-3 font-black text-[hsl(var(--hw-navy))]">Play</TactilePressable>{legal.some(a=>a.type==='pass-drawn')?<TactilePressable onClick={()=>commit({type:'pass-drawn',actor:HUMAN})} className="rounded-2xl bg-white/7 py-3 font-black text-white shadow-none">Pass</TactilePressable>:<TactilePressable disabled={!legal.some(a=>a.type==='draw')} onClick={()=>commit({type:'draw',actor:HUMAN})} className="rounded-2xl bg-white/7 py-3 font-black text-white shadow-none">Draw</TactilePressable>}</div>{state.lastEvent?.lastSparkPenalty&&<p className="mt-2 text-center text-xs hw-family-ruby">Missed Last Spark — two-card penalty.</p>}</div>;
}

function Completion({id,state,engine,nextRound,newGame}){const complete=engine.isTerminal(state)||state.roundComplete;if(!complete)return null;const result=engine.result(state);const roundMode=['crazy-eights','color-clash'].includes(id)&&state.roundComplete&&!state.matchComplete;return <GlassSurface strength={4} goldEdge className="mt-3 rounded-[1.6rem] p-5 text-center"><Trophy size={34} className="mx-auto hw-family-gold"/><h3 className="mt-2 font-heading text-2xl font-black text-white">{result?.draw?'Draw':(result?.winners||state.winners||[]).includes(HUMAN)||state.roundResult?.winner===HUMAN?'You win!':'Game complete'}</h3><p className="mt-1 text-xs text-white/45">{roundMode?'Scores carry into the next full round.':'Complete game result recorded to HoldWise mastery.'}</p><div className="mt-4 grid grid-cols-2 gap-2">{roundMode&&<TactilePressable onClick={nextRound} className="rounded-2xl bg-[hsl(var(--hw-gold))] py-3 font-black text-[hsl(var(--hw-navy))]">New Round</TactilePressable>}<TactilePressable onClick={newGame} className="rounded-2xl bg-white/7 py-3 font-black text-white shadow-none"><RotateCcw size={15} className="mr-1 inline"/>New Game</TactilePressable></div></GlassSurface>}
