name: HoldWiseAI
options:
  bundleIdPrefix: com.willywill
  deploymentTarget:
    iOS: "15.0"
  createIntermediateGroups: true
  defaultConfig: Debug
settings:
  base:
    SWIFT_VERSION: 5.0
    IPHONEOS_DEPLOYMENT_TARGET: 15.0
    MARKETING_VERSION: 1.4.0
    CURRENT_PROJECT_VERSION: 1
    TARGETED_DEVICE_FAMILY: "1,2"
    SUPPORTS_MACCATALYST: NO
    ENABLE_BITCODE: NO
    GENERATE_INFOPLIST_FILE: NO
    ENABLE_USER_SCRIPT_SANDBOXING: NO

targets:
  HoldWiseAI:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: Resources/LaunchScreen.storyboard
        buildPhase: resources
      - path: Resources/PrivacyInfo.xcprivacy
        buildPhase: resources
      - path: Resources/www
        type: folder
        buildPhase: resources
    settings:
      base:
        INFOPLIST_FILE: Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.willywill.holdwiseai
        PRODUCT_NAME: HoldWise AI
    scheme:
      gatherCoverageData: false

schemes:
  HoldWiseAI:
    build:
      targets:
        HoldWiseAI: all
    run:
      config: Debug
